version: '3'

services:
  db:
    image: mysql:8
    container_name: exambuddy-mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: docker.mitrasinovic.co.uk/exambuddy-wp
    container_name: exambuddy-wp
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.21.0-alpine
    container_name: exambuddy-nginx
    restart: unless-stopped
    expose:
      - 80
    labels:
      traefik.enable: true
      traefik.http.routers.exambuddy-wp.rule: Host(`wp.exambuddy.co.uk`)
      traefik.http.routers.exambuddy-wp.tls: true
      traefik.http.routers.exambuddy-wp.middlewares: https_redirect@file
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - app-network
      - traefik-proxy

volumes:
  wordpress:
  dbdata:

networks:
  traefik-proxy:
    external: true
  app-network:
    driver: bridge
